### ISSUE TITLE
Change map description to modal

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/imaginedsf#61]
1. because of the popup delay, it feels sluggish. what is the strategy here? I wonder if going back to a (i) button might be more effective?

2. I think an (x) button to close the popups would be nice

3. on small screensizes, the popups appear behind the map controls - they should be on the top level

**Comment by codyml** [comment]
- Add button to click that toggles the panel visibility instead of having it appear on hover.
  - Button design TBD
- Redesign panel so it appears as an underlay beneath the proposal map panel with a visual indicator (à la WP admin?) for the proposal map that it's describing.
  - Try darker background, perhaps same as deselected panel tabs
  - Should also appear beneath map controls
  - Should have a close button
  - Appearance for basemaps TBD

**Comment by codyml** [comment]
Design required:
- Button
- Panel
- Panel on basemaps

**Comment by codyml** [comment]
Includes #70 and #75

**Comment by codyml** [comment]
Clicking a button will close modal

**Comment by codyml** [comment]
Recommended basemap button should only appear if the recommended basemap exists
