### ISSUE TITLE
Make maps without bounds never hidden

### ISSUE THREAD

**Issue by cartosattva** [cestastanford/imaginedsf#84]
This may be a temporary problem that has to do with just making sure we have the right plans in the right places - but I noticed this because I had "only show plans" checked and the USCS Coast Survey map disappeared from the list but not from the viewing area. Then, I couldn't turn it off!

**Comment by codyml** [comment]
...in the Proposal Maps panel when the checkbox is checked.  Currently they're always hidden when  the checkbox is checked.

**Comment by codyml** [comment]
Bug that will be fixed when this issue is fixed: If a visible map doesn't have bounds and the checkbox is checked, the badge will not reflect that map.   [Example state hash](#eyJtYXBTdGF0ZSI6eyJlbmFibGVkIjp7IjI3MCI6ZmFsc2UsIjI3MSI6ZmFsc2UsIjI3MyI6ZmFsc2UsIjI3NCI6ZmFsc2UsIjI3NSI6ZmFsc2UsIjI5OSI6ZmFsc2UsIjMwMCI6ZmFsc2UsIjMwMSI6ZmFsc2UsIjMwMiI6ZmFsc2UsIjMwMyI6ZmFsc2UsIjMwNCI6ZmFsc2UsIjMwNSI6ZmFsc2UsIjMxMCI6ZmFsc2UsIjMxMiI6dHJ1ZSwiMzEzIjpmYWxzZSwiNDI1IjpmYWxzZSwiNDI3Ijp0cnVlLCI0MzAiOmZhbHNlfSwib3BhY2l0eSI6eyIyNzAiOjEsIjI3MSI6MSwiMjczIjoxLCIyNzQiOjEsIjI3NSI6MSwiMjk5IjoxLCIzMDAiOjEsIjMwMSI6MSwiMzAyIjoxLCIzMDMiOjEsIjMwNCI6MSwiMzA1IjoxLCIzMTAiOjEsIjMxMiI6MSwiMzEzIjoxLCI0MjUiOjEsIjQyNyI6MSwiNDMwIjoxfSwiYm91bmRzIjpbWzM3Ljc3MjA5Njk0OTEyNTg0NiwtMTIyLjQ1NTUyOTU2ODE1ODg4XSxbMzcuNzMyMTQ4NjAwODE4NjU0LC0xMjIuNDIxNDM4MDMyNzA3OTRdXX19)
